export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_SUCCESS = 'GET_SUCCESS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
//Course
export const GET_CURRENT_COURSES = 'GET_CURRENT_COURSES';
//Exercise
export const GET_EXERCISE_LIST = 'GET_EXERCISE_LIST';
export const GET_COMMENT = 'GET_COMMENT';
//Quiz
export const GET_CURRENT_TESTQUIZ = 'GET_CURRENT_TESTQUIZ';
export const GET_DETEAIL_QUIZ = 'GET_CURRENT_TESTQUIZ';
//Attendance
export const GET_PROFILE = 'GET_PROFILE';
export const GET_ATTENDANCE = 'GET_ATTENDANCE';
export const CLEAR_ATTENDANCE = 'CLEAR_ATTENDANCE';
//User
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_USERS = 'GET_USERS';
export const CLEAR_USER = 'CLEAR_USER';
//Schedule
export const GET_SCHEDULE = 'GET_SCHEDULE';
export const GET_SUBMISSION = 'GET_SUBMISSION';
export const DEL_SUBMISSION = 'DEL_SUBMISSION';
export const GET_STUDENT = 'GET_STUDENT';
export const GET_STUDENT_COURSES = 'GET_STUDENT_COURSES';
export const GET_STUDENT_ABSENT_LIST = 'GET_STUDENT_ABSENT_LIST';
